workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    simple-payments-api:
        inputs:
            - location: ../../simple-payments/openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/wiremock/wiremock/simple-payments-api
targets:
    my-first-target:
        target: java
        source: simple-payments-api
