openapi: 3.0.1
info:
  title: Simple demo payments API
  description: A simple payments API supporting charges and customers
  version: 1.0.0
servers:
- url: https://simple-payments.wiremockapi.cloud
paths:
  /customers/{customerId}:
    get:
      description: Gets a customer by ID.
      operationId: getCustomerById
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: detail
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - full
          - summary
      responses:
        "200":
          description: Simple demo payments API stub 2
          content:
            application/json:
              schema:
                required:
                - firstName
                - id
                - lastName
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                    example: tom@wiremock.org
              examples:
                example-one:
                  summary: First customer example
                  value:
                    id: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
                    firstName: Tom
                    lastName: Akehurst
                  x-parameter-values:
                    id: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
                    detail: full
                Simple demo payments API stub 2:
                  value: |-
                    {
                        "id": "1c777b16-2a24-47c1-8b24-a38cf96c66e0",
                        "firstName": "Tom",
                        "lastName": "Akehurst"
                    }
    put:
      description: Updates customers by customerId.
      operationId: putCustomersByCustomerId
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: detail
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - full
          - summary
      requestBody:
        content:
          application/json:
            schema:
              required:
              - address
              - departmentCode
              - email
              - firstName
              - lastName
              type: object
              properties:
                firstName:
                  type: string
                  example: Willette
                lastName:
                  type: string
                  example: Hauck
                departmentCode:
                  type: string
                  example: zwj
                email:
                  type: string
                  example: treb0oiqz3253s654yq3xx2pjxlbdmjs4scxrji034j9dmwerguisw7h26xm2zyiv1glen9vy6zxnoptege8n78wbaez2u3nkxd3sq56dtyrx5qmtain8vhp2
                address:
                  type: string
                  example: 5ywgj9tz6lydy3kwyg8nwr3il5d8rfb90byy8cir4mkjtznv9561gg7
            examples:
              Update customer:
                value: |-
                  {
                    "firstName" : "Elias",
                    "lastName" : "Deckow",
                    "address" : "rwwtb6h3j8dzv9n513mod6f8tqegrxy19v5yygz8foam59mje9v43lcu078w8loa9dne0myc2zxd2m8wi6rmh7wwgpebqwbsbj3acns90s6ha48cjv7l8evut301aeubecc2n9v1xouaqekvfjq60ffgvpup73ezgxm5wjcrlygjtu6m3fwcoayju8p8",
                    "departmentCode" : "yf702y72gwi3qxtrjl4d4iqab8o2z3jok7xlg9k542vo75agsapce28jcf6r7gwz5ne4sf5vw40uup8iqtq477p77t69215cp5hl48zwb6cauidnscwoz2e1b0ztdnmyqjepdh3jdwnugco0alasuetg46h2",
                    "email" : "w0ox0756fhklml2voto44ei3pv50zjjuyn4utw0tpuwsdhfj8df9xt4ieylf8jt635p3n32ozjhdd9w3ftnzhlf7xecd"
                  }
        required: true
      responses:
        "200":
          description: Update customer
          content:
            application/json:
              schema:
                required:
                - firstName
                - id
                - lastName
                type: object
                properties:
                  id:
                    type: string
                    example: 1c777b16-2a24-47c1-8b24-a38cf96c66e0
                  firstName:
                    type: string
                    example: Tom
                  lastName:
                    type: string
                    example: Akehurst
                  email:
                    type: string
                    example: tom@wiremock.org
                x-wiremock-hash: 1727538486
              examples:
                Update customer:
                  value: |
                    {
                      "id": "1c777b16-2a24-47c1-8b24-a38cf96c66e0",
                      "firstName": "Tom",
                      "lastName": "Akehurst",
                      "email": "tom@wiremock.org"
                    }
  /charges:
    post:
      description: Create a new charge.
      operationId: postCharges
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - amount
              - currency
              - customerId
              type: object
              properties:
                amount:
                  type: integer
                  format: int32
                  example: 350
                currency:
                  type: string
                  example: gbp
                customerId:
                  type: string
                  example: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
            examples:
              Create charge:
                value: |-
                  {
                      "amount": 350,
                      "currency": "gbp",
                      "customerId": "5931ed73-dcd4-4e24-ad24-975ac288fa7f"
                  }
        required: true
      responses:
        "200":
          description: Create charge
          content:
            application/json:
              schema:
                required:
                - amount
                - created
                - currency
                - customer
                - id
                - status
                type: object
                properties:
                  id:
                    type: string
                    example: 9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3
                  amount:
                    type: integer
                    format: int32
                    example: 350
                  currency:
                    type: string
                    example: gbp
                  customer:
                    type: string
                    example: /customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f
                  created:
                    type: string
                    example: 2023-09-03T10:31:22Z
                  status:
                    type: string
                    example: pending
                x-wiremock-hash: 366003811
              examples:
                Create charge:
                  value: |-
                    {
                        "id": "9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3",
                        "amount": 350,
                        "currency": "gbp",
                        "customer": "/customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f",
                        "created": "2023-09-03T10:31:22Z",
                        "status": "pending"
                    }
  /charges/{chargeId}:
    get:
      description: Get charges by chargeId.
      operationId: getChargesByChargeId
      parameters:
      - name: chargeId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
        example: 1c777b16-2a24-47c1-8b24-a38cf96c66e0
      responses:
        "200":
          description: Get charges by chargeId. - Get charge by ID
          content:
            application/json:
              schema:
                required:
                - amount
                - created
                - currency
                - customer
                - id
                - status
                type: object
                properties:
                  id:
                    type: string
                    example: 9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3
                  amount:
                    type: integer
                    format: int32
                    example: 350
                  currency:
                    type: string
                    example: gbp
                  customer:
                    type: string
                    example: /customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f
                  created:
                    type: string
                    example: 2023-09-03T10:31:22Z
                  status:
                    type: string
                    example: pending
                x-wiremock-hash: 366003811
              examples:
                Get charge by ID:
                  value: |-
                    {
                        "id": "9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3",
                        "amount": 350,
                        "currency": "gbp",
                        "customer": "/customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f",
                        "created": "2023-09-03T10:31:22Z",
                        "status": "pending"
                    }
  /invoices/{invoiceId}:
    get:
      description: Get an invoice by invoice ID.
      operationId: getInvoicesByInvoiceId
      parameters:
      - name: invoiceId
        in: path
        required: true
      responses:
        "200":
          description: Get invoice by ID
          content:
            application/json:
              schema:
                required:
                - charge
                - currency
                - id
                - totalAmount
                type: object
                properties:
                  id:
                    type: string
                    example: 80b4ee05-ff3e-4278-a98f-35f397657212
                  totalAmount:
                    type: integer
                    format: int32
                    example: 350
                  currency:
                    type: string
                    example: gbp
                  charge:
                    type: string
                    example: /charges/9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3
                x-wiremock-hash: -1535570859
              examples:
                Get invoice by ID:
                  value: |-
                    {
                        "id": "80b4ee05-ff3e-4278-a98f-35f397657212",
                        "totalAmount": 350,
                        "currency": "gbp",
                        "charge": "/charges/9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3"
                    }
