openapi: 3.0.1
info:
  title: Simple demo payments API
  version: 1.0.0
servers:
- url: https://simple-payments.wiremockapi.cloud
paths:
  /customers/{customerId}:
    get:
      description: Gets a customer by ID.
      operationId: getCustomerById
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: detail
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - full
          - summary
      responses:
        "200":
          description: Simple demo payments API stub 2
          content:
            application/json:
              schema:
                required:
                - firstName
                - id
                - lastName
                type: object
                properties:
                  id:
                    type: string
                    format: uuid
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                    example: tom@wiremock.org
              examples:
                example-one:
                  summary: First customer example
                  value:
                    id: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
                    firstName: Tom
                    lastName: Akehurst
                  x-parameter-values:
                    id: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
                    detail: full
                Simple demo payments API stub 2:
                  value: |-
                    {
                        "id": "1c777b16-2a24-47c1-8b24-a38cf96c66e0",
                        "firstName": "Tom",
                        "lastName": "Akehurst"
                    }
    put:
      description: Updates customers by customerId.
      operationId: putCustomersByCustomerId
      parameters:
      - name: customerId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
      - name: detail
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - full
          - summary
      requestBody:
        content:
          application/json:
            schema:
              required:
              - departmentCode
              - email
              - firstName
              - lastName
              type: object
              properties:
                firstName:
                  type: string
                  example: Willette
                lastName:
                  type: string
                  example: Hauck
                departmentCode:
                  type: string
                  example: ulhmlhnrsrf4xws25hdqdf1vfmlubgrlexkiuovakh1ijrh6uimpi1vdqabw46u51gk90jxd3fx4rafbs0x5qwb6mrlc0y74ap87qsyhi5frlwc5t1zzkcj
                email:
                  type: string
                  example: kv2c1mo6fuaer443qc5icj7tthircz
            examples:
              Update customer:
                value: |-
                  {
                    "firstName" : "Elias",
                    "lastName" : "Deckow",
                    "departmentCode" : "rm6jelbfoaqrf163fgme3ob6fxqt4d1e7lakcc7vzh2pes193obkm4lwmobuk72r",
                    "email" : "e3wrho3th7eg4u5pgeib0wyjpyj0nstcigjj82tasutxaofq2o5kfngfx312isxdbp87vgwjmmamwndz4m137uguirvw98c1yjjme83ozb34g4aypxkwen3r3b7sroe4zxcqi022m3ynokbfuvbz0cgaeqr3bk"
                  }
        required: true
      responses:
        "200":
          description: Update customer
          content:
            application/json:
              schema:
                required:
                - email
                - firstName
                - id
                - lastName
                type: object
                properties:
                  id:
                    type: string
                    example: 1c777b16-2a24-47c1-8b24-a38cf96c66e0
                  firstName:
                    type: string
                    example: Tom
                  lastName:
                    type: string
                    example: Akehurst
                  email:
                    type: string
                    example: tom@wiremock.org
                x-wiremock-hash: 1166170928
              examples:
                Update customer:
                  value: |
                    {
                      "id": "1c777b16-2a24-47c1-8b24-a38cf96c66e0",
                      "firstName": "Tom",
                      "lastName": "Akehurst",
                      "email": "tom@wiremock.org"
                    }
  /charges:
    post:
      description: Create a new charge.
      operationId: postCharges
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              required:
              - amount
              - currency
              - customerId
              type: object
              properties:
                amount:
                  type: integer
                  format: int32
                  example: 350
                currency:
                  type: string
                  example: gbp
                customerId:
                  type: string
                  example: 5931ed73-dcd4-4e24-ad24-975ac288fa7f
            examples:
              Create charge:
                value: |-
                  {
                      "amount": 350,
                      "currency": "gbp",
                      "customerId": "5931ed73-dcd4-4e24-ad24-975ac288fa7f"
                  }
        required: true
      responses:
        "200":
          description: Create charge
          content:
            application/json:
              schema:
                required:
                - amount
                - created
                - currency
                - customer
                - id
                - status
                type: object
                properties:
                  id:
                    type: string
                    example: 9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3
                  amount:
                    type: integer
                    format: int32
                    example: 350
                  currency:
                    type: string
                    example: gbp
                  customer:
                    type: string
                    example: /customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f
                  created:
                    type: string
                    example: 2023-09-03T10:31:22Z
                  status:
                    type: string
                    example: pending
                x-wiremock-hash: 366003811
              examples:
                Create charge:
                  value: |-
                    {
                        "id": "9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3",
                        "amount": 350,
                        "currency": "gbp",
                        "customer": "/customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f",
                        "created": "2023-09-03T10:31:22Z",
                        "status": "pending"
                    }
  /charges/{chargeId}:
    get:
      description: Get charges by chargeId.
      operationId: getChargesByChargeId
      parameters:
      - name: chargeId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          format: uuid
        example: 1c777b16-2a24-47c1-8b24-a38cf96c66e0
      responses:
        "200":
          description: Get charges by chargeId. - Get charge by ID
          content:
            application/json:
              schema:
                required:
                - amount
                - created
                - currency
                - customer
                - id
                - status
                type: object
                properties:
                  id:
                    type: string
                    example: 9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3
                  amount:
                    type: integer
                    format: int32
                    example: 350
                  currency:
                    type: string
                    example: gbp
                  customer:
                    type: string
                    example: /customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f
                  created:
                    type: string
                    example: 2023-09-03T10:31:22Z
                  status:
                    type: string
                    example: pending
                x-wiremock-hash: 366003811
              examples:
                Get charge by ID:
                  value: |-
                    {
                        "id": "9b6b418a-0b59-486c-a4a3-cd0f1cdbf0b3",
                        "amount": 350,
                        "currency": "gbp",
                        "customer": "/customers/5931ed73-dcd4-4e24-ad24-975ac288fa7f",
                        "created": "2023-09-03T10:31:22Z",
                        "status": "pending"
                    }
