/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import io.wiremock.demos.simple_payments_sdk.models.errors.SDKError;
import io.wiremock.demos.simple_payments_sdk.utils.LazySingletonValue;
import io.wiremock.demos.simple_payments_sdk.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetChargesByChargeIdRequestBuilder {

    private String chargeId;
    private final SDKMethodInterfaces.MethodCallGetChargesByChargeId sdk;

    public GetChargesByChargeIdRequestBuilder(SDKMethodInterfaces.MethodCallGetChargesByChargeId sdk) {
        this.sdk = sdk;
    }

    public GetChargesByChargeIdRequestBuilder chargeId(String chargeId) {
        Utils.checkNotNull(chargeId, "chargeId");
        this.chargeId = chargeId;
        return this;
    }

    public GetChargesByChargeIdResponse call() throws Exception {

        return sdk.getChargesByChargeId(
            chargeId);
    }
}
