/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import io.wiremock.demos.simple_payments_sdk.models.errors.SDKError;
import io.wiremock.demos.simple_payments_sdk.utils.LazySingletonValue;
import io.wiremock.demos.simple_payments_sdk.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class GetCustomerByIdRequestBuilder {

    private Long id;
    private Detail detail;
    private final SDKMethodInterfaces.MethodCallGetCustomerById sdk;

    public GetCustomerByIdRequestBuilder(SDKMethodInterfaces.MethodCallGetCustomerById sdk) {
        this.sdk = sdk;
    }

    public GetCustomerByIdRequestBuilder id(long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public GetCustomerByIdRequestBuilder detail(Detail detail) {
        Utils.checkNotNull(detail, "detail");
        this.detail = detail;
        return this;
    }

    public GetCustomerByIdResponse call() throws Exception {

        return sdk.getCustomerById(
            id,
            detail);
    }
}
