/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import io.wiremock.demos.simple_payments_sdk.utils.SpeakeasyMetadata;
import io.wiremock.demos.simple_payments_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class GetCustomerByIdRequest {

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private long id;

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=detail")
    private Detail detail;

    @JsonCreator
    public GetCustomerByIdRequest(
            long id,
            Detail detail) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(detail, "detail");
        this.id = id;
        this.detail = detail;
    }

    @JsonIgnore
    public long id() {
        return id;
    }

    @JsonIgnore
    public Detail detail() {
        return detail;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public GetCustomerByIdRequest withId(long id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public GetCustomerByIdRequest withDetail(Detail detail) {
        Utils.checkNotNull(detail, "detail");
        this.detail = detail;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetCustomerByIdRequest other = (GetCustomerByIdRequest) o;
        return 
            java.util.Objects.deepEquals(this.id, other.id) &&
            java.util.Objects.deepEquals(this.detail, other.detail);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            id,
            detail);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetCustomerByIdRequest.class,
                "id", id,
                "detail", detail);
    }
    
    public final static class Builder {
 
        private Long id;
 
        private Detail detail;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder id(long id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder detail(Detail detail) {
            Utils.checkNotNull(detail, "detail");
            this.detail = detail;
            return this;
        }
        
        public GetCustomerByIdRequest build() {
            return new GetCustomerByIdRequest(
                id,
                detail);
        }
    }
}

