/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import io.wiremock.demos.simple_payments_sdk.models.errors.SDKError;
import io.wiremock.demos.simple_payments_sdk.utils.LazySingletonValue;
import io.wiremock.demos.simple_payments_sdk.utils.Utils;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import java.util.stream.Stream;
import org.openapitools.jackson.nullable.JsonNullable;


public class PutCustomersByCustomerIdRequestBuilder {

    private String customerId;
    private QueryParamDetail detail;
    private PutCustomersByCustomerIdRequestBody requestBody;
    private final SDKMethodInterfaces.MethodCallPutCustomersByCustomerId sdk;

    public PutCustomersByCustomerIdRequestBuilder(SDKMethodInterfaces.MethodCallPutCustomersByCustomerId sdk) {
        this.sdk = sdk;
    }

    public PutCustomersByCustomerIdRequestBuilder customerId(String customerId) {
        Utils.checkNotNull(customerId, "customerId");
        this.customerId = customerId;
        return this;
    }

    public PutCustomersByCustomerIdRequestBuilder detail(QueryParamDetail detail) {
        Utils.checkNotNull(detail, "detail");
        this.detail = detail;
        return this;
    }

    public PutCustomersByCustomerIdRequestBuilder requestBody(PutCustomersByCustomerIdRequestBody requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public PutCustomersByCustomerIdResponse call() throws Exception {

        return sdk.putCustomersByCustomerId(
            customerId,
            detail,
            requestBody);
    }
}
