/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.operations;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class SDKMethodInterfaces {

    public interface MethodCallGetCustomerById {
        io.wiremock.demos.simple_payments_sdk.models.operations.GetCustomerByIdResponse getCustomerById(
            long id,
            io.wiremock.demos.simple_payments_sdk.models.operations.Detail detail) throws Exception;
    }


    public interface MethodCallPostCharges {
        io.wiremock.demos.simple_payments_sdk.models.operations.PostChargesResponse postCharges(
            io.wiremock.demos.simple_payments_sdk.models.operations.PostChargesRequestBody request) throws Exception;
    }

}
