/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk;

import io.wiremock.demos.simple_payments_sdk.utils.Hook.SdkInitData;
import io.wiremock.demos.simple_payments_sdk.utils.HTTPClient;
import io.wiremock.demos.simple_payments_sdk.utils.RetryConfig;
import java.util.Optional;

class SDKConfiguration {
    public SecuritySource securitySource;
    
    public Optional<SecuritySource> securitySource() {
        return Optional.ofNullable(securitySource);
    }
    
    public HTTPClient defaultClient;
      public String serverUrl;
    public int serverIdx = 0;
    public String language = "java";
    public String openapiDocVersion = "1.0.0";
    public String sdkVersion = "0.0.1";
    public String genVersion = "2.326.3";
    public String userAgent = "speakeasy-sdk/java 0.0.1 2.326.3 1.0.0 io.wiremock.demos.simple_payments_sdk";

    private io.wiremock.demos.simple_payments_sdk.utils.Hooks _hooks = new io.wiremock.demos.simple_payments_sdk.utils.Hooks();

    public io.wiremock.demos.simple_payments_sdk.utils.Hooks hooks() {
        return _hooks;
    }

    public void setHooks(io.wiremock.demos.simple_payments_sdk.utils.Hooks hooks) {
        this._hooks = hooks;
    }

    /** 
     * Initializes state (for example hooks).
     **/
    public void initialize() {

    }

    
    
    public Optional<RetryConfig> retryConfig = Optional.empty();
}
