/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package io.wiremock.demos.simple_payments_sdk.models.components;

public class Security {
    // Security not configured but we create this class 
    // to help with SecuritySource references in sdk hook context
}